"""
gen_cues.py · 读 audio/beat_XX.mp3 的真实时长，生成 cues.ts / cues.json

用法：
  python gen_cues.py

输入：./beats.json + ./audio/beat_XX.mp3
输出：./cues.json + ./remotion/src/cues.ts + ./remotion/public/audio/voiceover.mp3
"""
import json, shutil, subprocess
from pathlib import Path

BEATS_FILE   = Path("./beats.json")
AUDIO_DIR    = Path("./audio")
CUES_JSON    = Path("./cues.json")
CUES_TS      = Path("./remotion/src/cues.ts")
VOICEOVER    = Path("./remotion/public/audio/voiceover.mp3")
FPS          = 30


def _find(binary: str) -> str:
    p = shutil.which(binary)
    if p:
        return p
    # remotion 自带的 compositor 二进制
    candidates = list(Path("./remotion/node_modules/@remotion").glob(
        f"compositor-*/{binary}*"))
    if candidates:
        return str(candidates[0])
    raise FileNotFoundError(f"{binary} 未找到。请先 cd remotion && npm install")


def probe_duration(mp3: Path) -> float:
    result = subprocess.run(
        [_find("ffprobe"), "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(mp3)],
        capture_output=True, text=True, check=True,
    )
    return float(result.stdout.strip())


def load_beats():
    raw = json.loads(BEATS_FILE.read_text(encoding="utf-8"))
    if isinstance(raw, dict) and "beats" in raw:
        return raw["beats"]
    return raw


def main():
    beats = load_beats()

    cues = []
    cursor = 0.0
    frame_cursor = 0

    for b in beats:
        bid = b["id"]
        mp3 = AUDIO_DIR / f"beat_{bid:02d}.mp3"
        if not mp3.exists():
            raise FileNotFoundError(f"缺失音频: {mp3}")
        dur = probe_duration(mp3)
        duration_frames = round(dur * FPS)

        cues.append({
            "id":             bid,
            "chapter":        b["chapter"],
            "text":           b["text"],
            "startSec":       cursor,
            "durationSec":    dur,
            "startFrame":     frame_cursor,
            "durationFrames": duration_frames,
        })
        cursor += dur
        frame_cursor += duration_frames

    CUES_JSON.write_text(json.dumps(cues, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"✅ {CUES_JSON}: {len(cues)} beats, total {cursor:.2f}s ({frame_cursor} frames)")

    CUES_TS.parent.mkdir(parents=True, exist_ok=True)
    chapters = {}
    for c in cues:
        ch = c["chapter"]
        if ch not in chapters:
            chapters[ch] = {"id": ch, "startFrame": c["startFrame"], "startSec": c["startSec"], "beats": []}
        chapters[ch]["beats"].append(c["id"])
        chapters[ch]["endFrame"] = c["startFrame"] + c["durationFrames"]
        chapters[ch]["endSec"] = c["startSec"] + c["durationSec"]
    chapter_list = [chapters[k] for k in sorted(chapters.keys())]

    ts = f"""// AUTO-GENERATED by gen_cues.py — DO NOT EDIT BY HAND
export const FPS = {FPS};
export const TOTAL_FRAMES = {frame_cursor};

export type Cue = {{
  id: number;
  chapter: number;
  text: string;
  startSec: number;
  durationSec: number;
  startFrame: number;
  durationFrames: number;
}};

export const CUES: Cue[] = {json.dumps(cues, ensure_ascii=False, indent=2)};

export type Chapter = {{
  id: number;
  startFrame: number;
  endFrame: number;
  startSec: number;
  endSec: number;
  beats: number[];
}};

export const CHAPTERS: Chapter[] = {json.dumps(chapter_list, indent=2)};
"""
    CUES_TS.write_text(ts, encoding="utf-8")
    print(f"✅ {CUES_TS}")

    VOICEOVER.parent.mkdir(parents=True, exist_ok=True)
    concat_list = Path("./_concat.txt")
    lines = []
    for b in cues:
        p = (AUDIO_DIR / ("beat_%02d.mp3" % b["id"])).resolve()
        lines.append("file '%s'" % p)
    concat_list.write_text("\n".join(lines), encoding="utf-8")
    subprocess.run(
        [_find("ffmpeg"), "-hide_banner", "-y", "-f", "concat", "-safe", "0",
         "-i", str(concat_list),
         "-c:a", "libmp3lame", "-b:a", "96k", "-ar", "24000", "-ac", "1",
         str(VOICEOVER)],
        check=True,
    )
    concat_list.unlink()
    print(f"✅ {VOICEOVER}")


if __name__ == "__main__":
    main()