import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/zhishixingqiu/": [
    "readme.md",
    "jianli",
    "paicli",
    "paiflow",
    "paismart",
    "paismart-go",
    "paicoding",
    "pmhub",
    "mianshi",
    "map",
    "qiuzhao-gongsi-mingdan",
  ],
  "/nice-article/itmind/": [
    "readme.md",
    "shangwang.md",
  ],

  // 你可以省略 .md 扩展名，以 / 结尾的路径会被推断为 /README.md(区分大小写)
  "/pdf/": [
    "java30day",
    "linux",
    "java",
    "programmer-111",
    "java-concurrent",
    "shejimoshi",
    "java-leetcode",
    "ali-java-shouce",
    "yuanyifeng-c-language",
    "bat-shuati",
    "os",
    "progit",
    "jianli",
  ],
  "/xuexiluxian/": [
    {
      text: "Java学习路线",
      prefix: "java/",
      collapsible: true,
      children: [
        "yitiaolong",
        "thread",
        "jvm",
      ],
    },
    "mysql",
    "redis",
    "c",
    "ccc",
    "python",
    "go",
    "os",
    "qianduan",
    "algorithm",
    "lanqiaobei",
    "bigdata",
    "android",
    "donet",
    "linux",
  ],
  "/sidebar/sanfene/": [
    "nixi",
    "mysql",
    "redis",
    "spring",
    "javase",
    "collection",
    "javathread",
    "jvm",
    "openclaw",
    "skills",
    "mybatis",
    "os",
    "network",
    "rocketmq",
    "fenbushi",
    "weifuwu",
    "shejimoshi",
    "linux",
  ],
  "/sidebar/itwanger/ai/": [
    {
      text: "AI Agent学习路线",
      link: "ai-agent-xuexiluxian",
    },
    {
      text: "Claude Code",
      collapsible: true,
      children: [
        "learn-claude-code",
        "claude-code-leak-agents",
        "claude-code-best-practice-beta",
        "claude-code-plugin-tutorial",
        "claude-code-agent-browser-automation",
        "claude-code-buddy",
        "cc-mingling",
        "claude-opus-gpt-codex-2026",
        "warp-claude-code",
      ],
    },
    {
      text: "Codex",
      collapsible: true,
      children: [
        "codex-desktop-review",
        "codex-april-2026-deep-review",
        "codex-chatgpt-mobile",
        "codex-update-2026-04",
        "codex-feishu-plugin",
        "codex-gpt54-chrome-devtools-mcp",
      ],
    },
    {
      text: "IDEA插件",
      collapsible: true,
      children: [
        "idea-codex",
        "cc-gui-idea",
        "cc-gui-plugin-review",
        "intellij-idea-ai-agent-review",
        "feisuan-javaai-agent-review",
      ],
    },
    {
      text: "Harness",
      collapsible: true,
      children: [
        "agent-cli-harness-opus",
        "agent-harness-engineering",
        "harness-engineering-review",
        "openharness-review",
        "claude-managed-agents-launch",
        "bmad-method-33k-stars-review",
      ],
    },
    {
      text: "Qoder",
      collapsible: true,
      children: [
        "qoder-1-0-quest-review",
        "qoder-experts-mode-ceping",
        "qoder-experts-mode-xiaohao",
        "qoder-skills-shice",
        "qoderwork-chrome-review",
        "qoderwork-practice-brief",
        "qoderwork-review",
        "qoderwork-review2",
        "qoderwork-spring-festival",
        "qoderwork-storage-cleanup",
      ],
    },
    {
      text: "Skills",
      collapsible: true,
      children: [
        "6-skills-recommend",
        "agent-skills-top10",
        "claude-skills-quanwei-jiedu",
        "skills-yuanli-jiaocheng",
        "minimax-skills-ceping",
        "skill-creator-deep-dive",
        "skillhub-iflytek",
        "skillhub-iflytek-new",
        "web-access-skill-review",
        "web-access-skill-review-wechat",
        "dumpling-skill",
      ],
    },
    {
      text: "RAG",
      collapsible: true,
      children: [
        "embedding-rerank-rag",
        "rag-to-agent-paicli",
      ],
    },
    {
      text: "OpenClaw",
      collapsible: true,
      children: [
        "openclaw-github-study-path",
        "openclaw-install-feishu",
        "openclaw-install-all-method",
        "openclaw-memory-system",
        "openclaw-multi-agent-member-review",
        "hermes-agent-context",
        "hermes-agent-install",
        "arkclaw-coding-plan-review",
        "astronclaw-install-guide",
        "astronclaw-review",
        "copaw-ali",
        "lobsterai-wangyi",
        "openclaw-first-lobster-gitcode-review",
        "openclaw-memory-skills-gitcode",
        "openclaw-wecom-tutorial",
        "picoclaw-dingding",
        "picoclaw-shizhan",
        "wechat-openclaw",
        "wechat-openclaw-android",
        "weclaw",
        "zeroclaw-review",
      ],
    },
    {
      text: "LLM",
      collapsible: true,
      children: [
        "deepseek-v4",
        "deepseek-v4-review",
        "glm-5-1-new",
        "glm-5-review",
        "glm-5-1",
        "glm51-vs-deepseekv4",
        "kimi-k25-shice",
        "kimi-k26-agent-swarm",
        "qwen3-5-plus-review",
        "wenxin-5-test",
        "chatglm-xuexidazi",
        "chatglm-xuexidazi-review",
        "deepseek-agent-hiring",
        "deepseek-tui-review",
        "glm5-paiswitch",
        "glm5-turbo-pingce",
        "karpathy-llm-wiki",
        "kimi-ok-computer-zhu-yuanzhang",
        "minicpm-v-46",
        "step-3-5-flash-2603-review",
        "step-flash-2603-xiaohao",
        "stepplan-paicli-paiagent",
        "yuanbaopai-review",
      ],
    },
    {
      text: "面试篇",
      collapsible: true,
      children: [
        "claude-agent-principle",
        "claude-code-mythos",
        "interviewer-learn-claude-code",
        "agent-mianshi",
        "anshui-yin-mianshi",
        "skills-mianshi-hangye",
        "rag-interview-questions",
        "paismart-rag-interview",
        "paismart-rag-mianshi",
        "rag-mysql-mianshi",
        "ai-mianshi-openclaw",
        "openclaw-interview-uninstall",
        "openclaw-jiagou-yuanli",
        "openclaw-memory-review",
        "openclaw-multi-agent",
        "langgraph4j-interview",
        "langgraph4j-paiagent",
        "paicli-interview-advanced",
      ],
    },
    {
      text: "AI工具",
      collapsible: true,
      children: [
        "ai-tools-2026",
        "aionui-review",
        "cli-agent-future",
        "cli-revolution",
        "evomap-review",
        "feishu-cli-tutorial",
        "opencli-review",
        "pony-alpha-review",
        "skywork-desktop-review",
        "nano-banana-2-lovart",
      ],
    },
    {
      text: "Token套餐",
      collapsible: true,
      children: [
        "free-token-api-guide",
        "rtk-token-killer",
        "agent-plan-paiagent",
        "volcano-coding-plan",
      ],
    },
    {
      text: "其他",
      collapsible: true,
      children: [
        "agent-workflow-8steps",
        "ai-infra-six-keywords",
        "ai-opensource-new-era",
        "cdn-cert-auto-renew",
        "moltbook-observation",
        "ruoyi-ai-review",
        "x-recommendation-algorithm",
        "harnessclaw-review",
        "harnessclaw-review-cc",
        "paicli-agent-interview",
      ],
    },
  ],
  "/sidebar/itwanger/paicli/": [
    "paicli-interview-productization",
    "paicli-interview-tool-security",
    "paicli-interview-prompt-skill",
    "paicli-interview-multi-model",
    "paicli-interview-memory-context",
    "paicli-interview-mcp",
    "paicli-interview-comprehensive",
    "paicli-interview-agent-core",
    "paicli-image-input",
    "paicli-skill-system",
    "paicli-cdp-session-reuse",
    "paicli-mcp-advanced",
    "paicli-chrome-devtools-mcp",
    "paicli-mcp",
    "paicli-websearch-webfetch",
    "paicli-multi-model",
    "paicli-async-parallel",
    "paicli-hitl",
    "paicli-multi-agent",
    "build-agent-p4-rag",
    "build-agent-p3-memory",
    "build-agent-p2-plan-execute",
    "build-agent-from-scratch",
  ],
  "/sidebar/sjtu/": [
    {
      text: "心得篇",
      link: "fly/",
    },
    {
      text: "立志篇",
      link: "li-zhi-pian/",
    },
    {
      text: "访谈篇",
      link: "fang-tan-ji//",
    },
    {
      text: "人生篇",
      link: "fu-lu/",
    },
    {
      text: "生存技巧篇",
      link: "sheng-cun-ji-qiao/",
    }
  ],
  // 必须放在最后面
  "/": [
    {
      text: "一、前言",
      link: "home",
    },
    {
      text: "二、Java基础",
      collapsible: true,
      children: [
        // readme小写一定要带上.md，否则找不到
        // Java核心开始
        {
          prefix: "overview/",
          text: "2.1 Java概述及环境配置",
          collapsible: true,
          children: [
          "readme.md",
          "what-is-java",
          "jdk-install-config",
          "IDEA-install-config",
          "hello-world",
          ],
        },
        {
          text: "2.2 Java语法基础",
          collapsible: true,
          children: [
          "basic-extra-meal/48-keywords",
          "basic-grammar/javadoc",
          "basic-grammar/basic-data-type",
          "basic-grammar/type-cast",
          "basic-extra-meal/int-cache",
          "basic-grammar/operator",
          "basic-grammar/flow-control",
          "basic-grammar/basic-exercise",
          ],
        },
        {
          text: "2.3 数组&字符串",
          collapsible: true,
          children: [
          "array/array",
          "array/double-array",
          "array/print",
          "string/string-source",
          "string/immutable",
          "string/constant-pool",
          "string/intern",
          "string/builder-buffer",
          "string/equals",
          "string/join",
          "string/split",
          ],
        },
        {
          text: "2.4 面向对象编程",
          collapsible: true,
          children: [
          "oo/object-class",
          "oo/package",
          "oo/var",
          "oo/method",
          "basic-extra-meal/varables",
          "oo/native-method",
          "oo/construct",
          "oo/access-control",
          "oo/code-init",
          "oo/abstract",
          "oo/interface",
          "oo/inner-class",
          "oo/encapsulation-inheritance-polymorphism",
          "oo/this-super",
          "oo/static",
          "oo/final",
          "basic-extra-meal/instanceof",
          "basic-extra-meal/immutable",
          "basic-extra-meal/override-overload",
          "basic-extra-meal/annotation",
          "basic-extra-meal/enum",
          ],
        },
        {
          text: "2.5 集合框架（容器）",
          collapsible: true,
          prefix: "collection/",
          children: [
          "gailan",
          "arraylist",
          "linkedlist",
          "stack",
          "hashmap",
          "linkedhashmap",
          "treemap",
          "arraydeque",
          "PriorityQueue",
          "time-complexity",
          "list-war-2",
          "generic",
          "iterator-iterable",
          "fail-fast",
          "comparable-omparator",
          "WeakHashMap",
          ],
        },
        {
          text: "2.6 Java IO",
          collapsible: true,
          prefix:"io/",
          children: [
          "shangtou",
          "file-path",
          "stream",
          "reader-writer",
          "buffer",
          "char-byte",
          "serialize",
          "Serializbale",
          "transient",
          "print",
          ],
        },
        {
          text: "2.7 异常处理",
          collapsible: true,
          prefix:"exception/",
          children: [
          "gailan",
          "try-with-resources",
          "shijian",
          "npe",
          "try-catch-xingneng",
          ],
        },
        {
          text: "2.8 常用工具类",
          collapsible: true,
          prefix:"common-tool/",
          children: [
            "scanner",
            "arrays",
            "StringUtils",
            "Objects",
            "collections",
            "hutool",
            "guava",
            "utils",
          ],
        },
        {
          text: "2.9 Java新特性",
          prefix: "java8/",
          link: "/java8/",
          collapsible: true,
          children: [
          "stream",
          "optional",
          "Lambda",
          "java14",
          ],
        },
        {
          text: "2.10 网络编程",
          collapsible: true,
          prefix: "socket/",
          children: [
            "network-base",
            "socket",
            "http",
          ],
        },
        {
          text: "2.11 NIO",
          collapsible: true,
          prefix: "nio/",
          children: [
            "nio-better-io",
            "BIONIOAIO",
            "buffer-channel",
            "paths-files",
            "network-connect",
            "moxing",
          ],
        },
        {
          text: "2.12 Java重要知识点",
          prefix:"basic-extra-meal/",
          collapsible: true,
          children: [
          "java-naming",
          "java-unicode",
          "box",
          "deep-copy",
          "hashcode",
          "pass-by-value",
          "true-generic",
          "fanshe",
          ],
        },
        {
          text: "2.13 并发编程",
          collapsible: true,
          prefix: "thread/",
          children: [
            "readme.md",
            "wangzhe-thread",
            "callable-future-futuretask",
            "thread-state-and-method",
            "thread-group-and-thread-priority",
            "why-need-thread",
            "thread-bring-some-problem",
            "jmm",
            "volatile",
            "synchronized-1",
            "synchronized",
            "pianxiangsuo",
            "cas",
            "aqs",
            "lock",
            "reentrantLock",
            "ReentrantReadWriteLock",
            "condition",
            "LockSupport",
            "map",
            "ConcurrentHashMap",
            "ConcurrentLinkedQueue",
            "BlockingQueue",
            "CopyOnWriteArrayList",
            "ThreadLocal",
            "pool",
            "ScheduledThreadPoolExecutor",
            "atomic",
            "Unsafe",
            "CountDownLatch",
            "fork-join",
            "shengchanzhe-xiaofeizhe",
          ],
        },
        {
          text: "2.14 JVM",
          prefix: "jvm/",
          collapsible: true,
          children: [
          "readme.md",
          "what-is-jvm",
          "how-run-java-code",
          "class-load",
          "class-file-jiegou",
          "bytecode",
          "vm-stack-register",
          "zijiema-zhiling",
          "stack-frame",
          "neicun-jiegou",
          "gc",
          "gc-collector",
          "whereis-the-object",
          "jit",
          "console-tools",
          "view-tools",
          "arthas",
          "oom",
          "cpu-percent-100",
          "zongjie",
          ],
        },
        //Java核心结束
      ],
    },
    {
      text: "三、AI Agent",
      collapsible: true,
      children: [
        "sidebar/itwanger/ai/ai-agent-xuexiluxian",
        {
          text: "3.1 Claude Code",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/learn-claude-code",
          ],
        },
        {
          text: "3.2 Codex",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/codex-desktop-review",
            "sidebar/itwanger/ai/codex-april-2026-deep-review",
            "sidebar/itwanger/ai/codex-chatgpt-mobile",
            "sidebar/itwanger/ai/codex-gpt54-chrome-devtools-mcp",
          ],
        },
        {
          text: "3.3 Harness",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/agent-cli-harness-opus",
            "sidebar/itwanger/ai/agent-harness-engineering",
            "sidebar/itwanger/ai/harness-engineering-review",
            "sidebar/itwanger/ai/openharness-review",
          ],
        },
        {
          text: "3.4 IDEA插件",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/idea-codex",
            "sidebar/itwanger/ai/cc-gui-idea",
            "sidebar/itwanger/ai/intellij-idea-ai-agent-review",
            "sidebar/itwanger/ai/feisuan-javaai-agent-review",
          ],
        },
        {
          text: "3.5 Qoder",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/qoder-1-0-quest-review",
            "sidebar/itwanger/ai/qoder-experts-mode-ceping",
            "sidebar/itwanger/ai/qoder-skills-shice",
            "sidebar/itwanger/ai/qoderwork-review",
          ],
        },
        {
          text: "3.6 Skills",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/6-skills-recommend",
            "sidebar/itwanger/ai/agent-skills-top10",
            "sidebar/itwanger/ai/claude-skills-quanwei-jiedu",
            "sidebar/itwanger/ai/skills-yuanli-jiaocheng",
          ],
        },
        {
          text: "3.7 RAG",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/embedding-rerank-rag",
          ],
        },
        {
          text: "3.8 OpenClaw",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/openclaw-github-study-path",
            "sidebar/itwanger/ai/openclaw-install-feishu",
            "sidebar/itwanger/ai/openclaw-memory-system",
            "sidebar/itwanger/ai/hermes-agent-context",
          ],
        },
        {
          text: "3.9 LLM",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/deepseek-v4",
            "sidebar/itwanger/ai/glm-5-1-new",
            "sidebar/itwanger/ai/glm51-vs-deepseekv4",
            "sidebar/itwanger/ai/kimi-k25-shice",
          ],
        },
        {
          text: "3.10 面试篇",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/claude-agent-principle",
            "sidebar/itwanger/ai/claude-code-mythos",
            "sidebar/itwanger/ai/interviewer-learn-claude-code",
            "sidebar/itwanger/ai/agent-mianshi",
            "sidebar/itwanger/ai/anshui-yin-mianshi",
            "sidebar/itwanger/ai/skills-mianshi-hangye",
            "sidebar/itwanger/ai/rag-interview-questions",
            "sidebar/itwanger/ai/paismart-rag-interview",
            "sidebar/itwanger/ai/paismart-rag-mianshi",
            "sidebar/itwanger/ai/rag-mysql-mianshi",
            "sidebar/itwanger/ai/ai-mianshi-openclaw",
            "sidebar/itwanger/ai/openclaw-interview-uninstall",
            "sidebar/itwanger/ai/openclaw-jiagou-yuanli",
            "sidebar/itwanger/ai/openclaw-memory-review",
            "sidebar/itwanger/ai/openclaw-multi-agent",
            "sidebar/itwanger/ai/langgraph4j-interview",
            "sidebar/itwanger/ai/langgraph4j-paiagent",
            "sidebar/itwanger/ai/paicli-interview-advanced",
          ],
        },
        {
          text: "3.11 AI工具",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/ai-tools-2026",
            "sidebar/itwanger/ai/cli-revolution",
            "sidebar/itwanger/ai/opencli-review",
            "sidebar/itwanger/ai/skywork-desktop-review",
          ],
        },
        {
          text: "3.12 Token套餐",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/free-token-api-guide",
            "sidebar/itwanger/ai/rtk-token-killer",
            "sidebar/itwanger/ai/agent-plan-paiagent",
            "sidebar/itwanger/ai/volcano-coding-plan",
          ],
        },
        {
          text: "3.13 其他",
          collapsible: true,
          children: [
            "sidebar/itwanger/ai/agent-workflow-8steps",
            "sidebar/itwanger/ai/ai-infra-six-keywords",
            "sidebar/itwanger/ai/ai-opensource-new-era",
            "sidebar/itwanger/ai/cdn-cert-auto-renew",
          ],
        },
      ],
    },
    {
      text: "四、Java进阶",
      collapsible: true,
      children: [
        {
          text: "3.1 开发/构建工具",
          collapsible: true,
          children: [
            {
              text: "3.1.1 IDE",
              collapsible: true,
              children: [
              "ide/4-debug-skill",
              "ide/xechat",
              "ide/shenji-chajian-10",
              ],
            },
            {
              text: "3.1.2 Maven",
              collapsible: true,
              children: [
              "maven/maven",
              ],
            },
            {
              text: "3.1.3 Git",
              collapsible: true,
              prefix: "git/",
              children: [
              "git-qiyuan",
              "port-22-to-443",
              ],
            },
            {
              text: "3.1.4 Nginx",
              children: [
                "nginx/nginx",
              ],
            },
          ],
        },
        {
          text: "3.2 辅助工具",
          collapsible: true,
          children: [
            "gongju/choco",
            "gongju/brew",
            "gongju/tabby",
            "gongju/warp",
            "gongju/windterm",
            "gongju/chiner",
            "gongju/DBeaver",
          ],
        },
        {
          text: "3.3 开源轮子",
          collapsible: true,
          children: [
            {
              text: "HTTP调用框架Forest",
              link: "gongju/forest",
            },
            {
              text: "单元测试Junit",
              link: "gongju/junit",
            },
            {
              text: "阿里开源的fastjson",
              link: "gongju/fastjson",
            },
            {
              text: "谷歌开源的Gson",
              link: "gongju/gson",
            },
            {
              text: "SpringBoot内置的Jackson",
              link: "gongju/jackson",
            },
            {
              text: "日志框架的鼻祖Log4j",
              link: "gongju/log4j",
            },
            {
              text: "高性能日志框架Log4j2",
              link: "gongju/log4j2",
            },
            {
              text: "Spring Boot内置的Logback",
              link: "gongju/logback",
            },
            {
              text: "日志门面SLF4J",
              link: "gongju/slf4j",
            },
            
          ],
        },
        {
          text: "3.4 Spring",
          collapsible: true,
          children: [
            "springboot/aop-log",
            "springboot/ioc",
          ],
        },
        {
          text: "3.5 Spring Boot",
          collapsible: true,
          children: [
            {
              text: "搭建第一个Spring Boot项目",
              link: "springboot/initializr",
            },
            "springboot/lombok",
            {
              text: "整合MySQL和Druid",
              link: "springboot/mysql-druid",
            },
            {
              text: "整合JPA",
              link: "springboot/jpa",
            },
            {
              text: "整合Thymeleaf",
              link: "springboot/thymeleaf",
            },
            {
              text: "开启事务支持",
              link: "springboot/transaction",
            },
            {
              text: "过滤器、拦截器、监听器",
              link: "springboot/Filter-Interceptor-Listener",
            },
            {
              text: "整合Redis实现缓存",
              link: "redis/redis-springboot",
            },
            {
              text: "整合Logback",
              link: "springboot/logback"
            },
            {
              text: "整合Swagger-UI",
              link: "springboot/swagger"
            },
            {
              text: "整合Knife4j",
              link: "gongju/knife4j"
            },
            {
              text: "整合SpringTask",
              link: "springboot/springtask"
            },
            {
              text: "整合MyBatis-Plus AutoGenerator",
              link: "kaiyuan/auto-generator",
            },
            "springboot/quartz",
            "springboot/mybatis",
            "springboot/docker",
            "springboot/macos-codingmore-run",
            "springboot/windows-codingmore-run",
            "springboot/linux-codingmore-run",
            "springboot/validator",
          ],
        },
        {
          text: "3.6 Netty",
          collapsible: true,
          children: [
            "netty/rumen",
          ],
        },
        {
          text: "3.7 MongoDB",
          collapsible: true,
          children: [
            "mongodb/rumen",
          ],
        },
        {
          text: "3.8 消息队列",
          collapsible: true,
          children: [
            {
              text: "RabbitMQ入门",
              link: "mq/rabbitmq-rumen"
            },
            {
              text: "如何保障消息不丢失",
              link: "mq/100-budiushi"
            },
            "mq/kafka",
          ],
        },
        {
          text: "3.9 微服务/分布式",
          collapsible: true,
          children: [
            {
              text: "Elasticsearch入门",
              link: "elasticsearch/rumen"
            },
            {
              text: "聊聊ZooKeeper",
              link: "zookeeper/jibenjieshao"
            },
            {
              text: "聊聊微服务网关",
              link: "microservice/api-wangguan"
            },
          ],
        },
      ],
    },
    {
      text: "五、MySQL",
      collapsible: true,
      prefix: "mysql/",
      children: [
        "install",
        "database",
        "table",
        "data-type",
        "charset",
        "bin",
        "column",
        "select-simple",
        "select-where",
        "redis-shuju-yizhixing",
        "lijie-shiwu",
        "shiwu-shixian",
      ],
    },
    {
      text: "六、Redis",
      collapsible: true,
      prefix: "redis/",
      children: [
        "install",
        "rumen",
        "xuebeng-chuantou-jichuan",
      ],
    },
    {
      text: "七、计算机基础",
      collapsible: true,
      prefix: "cs/",
      children: [
        {
          text: "计算机操作系统",
          link: "os",
        },
        {
          text: "计算机网络",
          link: "wangluo",
        },
      ],
    },
    {
      text: "八、求职面试",
      collapsible: true,
      children: [
        {
          text: "面试题&八股文",
          collapsible: true,
          prefix:"interview/",
          children: [
            "java-34",
            "java-hashmap-13",
            "mysql-60",
            "mysql-suoyin-15",
            "redis-12",
            "nginx-40",
            "dubbo-17",
            "kafka-40",
            "java-basic-baguwen",
            "java-thread-baguwen",
            "java-jvm-baguwen",
            "mianshiguan-bigfile-miaochuan",
            "mianshiguan-fenkufenbiao",
            "mianshiguan-youhuiquan",
          ],
        },
        {
          text: "优质面经",
          collapsible: true,
          prefix:"mianjing/",
          children: [
            "shanganaliyun",
            "shezynmjfxhelmtttjddd",
            "xuelybdzheloffer",
            "huanxgzl",
            "quzjlsspdx",
            "zheisnylzldhzd",
            "chengxyspnhxagzl",
          ],
        },
        {
          text: "面试准备",
          collapsible: true,
          children: [
            "nice-article/weixin/zijxjjdyfqzgl",
            "nice-article/weixin/miansmtgl",
            "nice-article/weixin/luoczbmsddyb",
            "nice-article/weixin/youdxzhhmjzlycfx",
          ],
        },
        {
          text: "城市选择",
          prefix: "cityselect/",
          collapsible: true,
          children: [
            "wuhan",
            "beijing",
            "chengdu",
            "guangzhou",
            "hangzhou",
            "nanjing",
            "qingdao",
            "shenzhen",
            "suzhou",
            "xian",
            "zhengzhou",
            "jinan",
            "hefei",
          ],
        },
      ],
    },
    {
      text: "九、学习建议",
      collapsible: true,
      prefix: "xuexijianyi/",
      children: [
          "LearnCS-ByYourself",
          "read-csapp",
          "electron-information-engineering",
          "gaokao-zhiyuan-cs",
          "test-programmer-read-books",
          "xiaozhao-java-should-master",
          "chengxuyuan-fuye",
          "ruhzfzdgzzcxcz",
          "gaobingfa-jingyan-hsmcomputer",
          "hr-xinzi",
          "35-weiji",
          "20ren-it-quma",
          "benkesheng-ali-tengxun",
          "408",
        ],
    },
    {
      text: "十、知识库搭建",
      collapsible: true,
      prefix: "szjy/",
      children: [
          "buy-cloud-server",
          "install-baota-mianban",
          "buy-domain",
          "record-domain",
          "https-domain",
        ],
    },
    {
      text: "十一、联系作者",
      collapsible: true,
      prefix: "about-the-author/",
      children: [
        "bzhan-10wan",
        "zhihu-1000wan",
        "csdn-1000wan",
        "readme.md",
      ],
    },
  ],
});
